### ISSUE TITLE
Run without parameters, mpdq crashes instead of displaying usage information

### ISSUE THREAD

**Issue by barndawgie** [jfreeland/mpdq#1]
```
jbarnard@BarndawgHome:~$ go version
go version go1.15.7 linux/amd64
jbarnard@BarndawgHome:~$ mpdq
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ec75d]
goroutine 1 [running]:
io/ioutil.readAll.func1(0xc0000e5cb8)
        /usr/local/go/src/io/ioutil/ioutil.go:30 +0x106
panic(0x9c5f60, 0xeacd60)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
bytes.(*Buffer).ReadFrom(0xc0000e5c40, 0x0, 0x0, 0xa4227b, 0x5, 0xc0000e5c78)
        /usr/local/go/src/bytes/buffer.go:204 +0x7d
io/ioutil.readAll(0x0, 0x0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:36 +0xe5
io/ioutil.ReadAll(...)
        /usr/local/go/src/io/ioutil/ioutil.go:45
github.com/jfreeland/mpdq/cmd.getManifest()
        /home/jbarnard/go/src/github.com/jfreeland/mpdq/cmd/root.go:75 +0xba
github.com/jfreeland/mpdq/cmd.glob..func5(0xeb51e0, 0xef5930, 0x0, 0x0)
        /home/jbarnard/go/src/github.com/jfreeland/mpdq/cmd/root.go:34 +0x25
github.com/spf13/cobra.(*Command).execute(0xeb51e0, 0xc0000a01b0, 0x0, 0x0, 0xeb51e0, 0xc0000a01b0)
        /home/jbarnard/go/src/github.com/spf13/cobra/command.go:834 +0x231
github.com/spf13/cobra.(*Command).ExecuteC(0xeb51e0, 0x446b8a, 0xe6f420, 0xc000000180)
        /home/jbarnard/go/src/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/jbarnard/go/src/github.com/spf13/cobra/command.go:895
github.com/jfreeland/mpdq/cmd.Execute()
        /home/jbarnard/go/src/github.com/jfreeland/mpdq/cmd/root.go:43 +0x31
main.main()
        /home/jbarnard/go/src/github.com/jfreeland/mpdq/main.go:8 +0x25
```

**Comment by barndawgie** [comment]
I doubt this is still relevant.
